[build]
  command   = "npm run build:web"
  publish   = ".next"
  functions = "api"

[build.environment]
  # Node runtime
  NODE_VERSION = "20.16.0"
  # Give Node a bit more memory
  NODE_OPTIONS = "--max-old-space-size=8192"

  # UI formatting flags (publicly exposed to your Next.js code)
  NEXT_PUBLIC_DECIMAL_PLACES_TOKEN   = "6"
  NEXT_PUBLIC_DECIMAL_PLACES_USD     = "2"
  NEXT_PUBLIC_SHOW_FULL_PRECISION    = "false"
  NEXT_PUBLIC_USE_COMMA_SEPARATOR    = "true"
  NEXT_PUBLIC_DESKTOP_FORMAT         = "full"

[build.processing]
  # keep Netlify from stripping your Next.js cache
  skip_processing = false
